export const questions = {
  moduleA: [
    {
      id: "q_mod_a_1",
      questionNumber: 1,
      totalInModule: 5,
      module: "A",
      moduleTitle: "SYSTEM KNOWLEDGE CHECK",
      prompt: "What is the output of an AND gate when one of its inputs is LOW?",
      options: [
        { key: "A", text: "HIGH" },
        { key: "B", text: "LOW" },
        { key: "C", text: "Floating" },
        { key: "D", text: "Undefined" },
      ],
      correctAnswer: "B",
      explanation: "An AND gate requires all inputs to be HIGH (1) to produce a HIGH output. If any input is LOW (0), the output is immediately LOW (0).",
    },
    {
      id: "q_mod_a_2",
      questionNumber: 2,
      totalInModule: 5,
      module: "A",
      moduleTitle: "SYSTEM KNOWLEDGE CHECK",
      prompt: "Which logic gate produces HIGH only when its two inputs are different?",
      options: [
        { key: "A", text: "AND" },
        { key: "B", text: "OR" },
        { key: "C", text: "NOT" },
        { key: "D", text: "XOR" },
      ],
      correctAnswer: "D",
      explanation: "An XOR (Exclusive OR) gate outputs HIGH (1) strictly when its inputs are distinct (0,1 or 1,0). When both inputs are identical (0,0 or 1,1), its output is LOW (0).",
    },
    {
      id: "q_mod_a_3",
      questionNumber: 3,
      totalInModule: 5,
      module: "A",
      moduleTitle: "SYSTEM KNOWLEDGE CHECK",
      prompt: "Which logic gate performs digital signal inversion where the output is the logical complement of the input?",
      options: [
        { key: "A", text: "Buffer gate" },
        { key: "B", text: "NOT gate (Inverter)" },
        { key: "C", text: "NAND gate" },
        { key: "D", text: "NOR gate" },
      ],
      correctAnswer: "B",
      explanation: "A NOT gate (Inverter) inverts the incoming binary signal: a HIGH (1) input yields a LOW (0) output, and a LOW (0) input yields a HIGH (1) output.",
    },
    {
      id: "q_mod_a_4",
      questionNumber: 4,
      totalInModule: 5,
      module: "A",
      moduleTitle: "SYSTEM KNOWLEDGE CHECK",
      prompt: "What is the output of a 2-input OR gate when input A is HIGH (1) and input B is LOW (0)?",
      options: [
        { key: "A", text: "LOW (0)" },
        { key: "B", text: "HIGH (1)" },
        { key: "C", text: "High-Impedance (Z)" },
        { key: "D", text: "Oscillating" },
      ],
      correctAnswer: "B",
      explanation: "An OR gate produces a HIGH (1) output if at least one of its inputs is HIGH. Thus, 1 OR 0 evaluates to 1.",
    },
    {
      id: "q_mod_a_5",
      questionNumber: 5,
      totalInModule: 5,
      module: "A",
      moduleTitle: "SYSTEM KNOWLEDGE CHECK",
      prompt: "Which universal logic gate produces a LOW (0) output ONLY when all of its inputs are HIGH (1)?",
      options: [
        { key: "A", text: "NOR gate" },
        { key: "B", text: "XOR gate" },
        { key: "C", text: "NAND gate" },
        { key: "D", text: "XNOR gate" },
      ],
      correctAnswer: "C",
      explanation: "A NAND gate is an inverted AND gate (NOT-AND). Its output is LOW (0) strictly when all inputs are 1; for all other input combinations, it outputs HIGH (1).",
    },
  ],

  moduleB: [
    {
      id: "q_mod_b_1",
      questionNumber: 1,
      totalInModule: 1,
      module: "B",
      moduleTitle: "CIRCUIT LOGIC VERIFICATION",
      prompt: "Which gate should be used when ALL required safety conditions must be TRUE for the final output to become HIGH?",
      options: [
        { key: "A", text: "AND" },
        { key: "B", text: "OR" },
        { key: "C", text: "XOR" },
        { key: "D", text: "NOT" },
      ],
      correctAnswer: "A",
      explanation: "An AND gate enforces a strict conjunction: every single monitored safety interlock signal must evaluate to TRUE (1) to produce an active SAFE output.",
    },
  ],

  moduleC: [
    {
      id: "q_mod_c_1",
      questionNumber: 1,
      totalInModule: 9,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "What should happen to the safety output if an emergency bypass is activated?",
      options: [
        { key: "A", text: "Remain HIGH" },
        { key: "B", text: "Become LOW" },
        { key: "C", text: "Toggle randomly" },
        { key: "D", text: "Increase voltage" },
      ],
      correctAnswer: "B",
      explanation: "In an industrial fail-safe interlock, activating a bypass or maintenance override must force the primary safety output LOW to inhibit hazardous operations.",
    },
    {
      id: "q_mod_c_2",
      questionNumber: 2,
      totalInModule: 9,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "In a fail-safe emergency system, what is the preferred behavior during an uncertain or unsafe condition?",
      options: [
        { key: "A", text: "Assume everything is safe" },
        { key: "B", text: "Disable all alarms" },
        { key: "C", text: "Move the system toward a safe state" },
        { key: "D", text: "Ignore the sensor" },
      ],
      correctAnswer: "C",
      explanation: "Fail-safe engineering dictates that on any component malfunction, signal loss, or sensor anomaly, the interlock automatically defaults to the de-energized or safest shutdown state.",
    },
    {
      id: "q_mod_c_3",
      questionNumber: 3,
      totalInModule: 9,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "Why are emergency stop (E-Stop) circuits wired using Normally Closed (NC) contacts rather than Normally Open (NO)?",
      options: [
        { key: "A", text: "To minimize energy consumption during machine operation" },
        { key: "B", text: "So a broken wire or power loss immediately triggers an emergency stop" },
        { key: "C", text: "To eliminate the need for grounding wires in the control panel" },
        { key: "D", text: "To speed up relay reaction time by bypassing resistors" },
      ],
      correctAnswer: "B",
      explanation: "Normally Closed (NC) contacts ensure de-energize-to-trip safety: if an E-Stop wire is severed, broken, or unplugged, the circuit opens immediately and brings the machinery to a safe halt.",
    },
    {
      id: "q_mod_c_4",
      questionNumber: 4,
      totalInModule: 9,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "What is the primary objective of implementing 'redundancy' (dual-channel design) in safety interlock architectures?",
      options: [
        { key: "A", text: "Preventing a single hardware or sensor failure from disabling safety protection" },
        { key: "B", text: "Increasing PLC CPU processing speed and network throughput" },
        { key: "C", text: "Reducing physical manufacturing space in the electrical cabinet" },
        { key: "D", text: "Allowing technicians to bypass authentication security codes" },
      ],
      correctAnswer: "A",
      explanation: "Redundancy prevents single-point-of-failure vulnerabilities: if one sensor or channel fails or shorts, the independent parallel channel still detects the hazard and guarantees fail-safe shutdown.",
    },
    {
      id: "q_mod_c_5",
      questionNumber: 5,
      totalInModule: 9,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "What is 'discrepancy time monitoring' in dual-channel safety interlock circuits?",
      options: [
        { key: "A", text: "Measuring the delay between shift rotations of human operators" },
        { key: "B", text: "Verifying that both redundant safety channels transition to the safe state within an allowed time window" },
        { key: "C", text: "Synchronizing server time across distributed SCADA nodes" },
        { key: "D", text: "Calculating the battery backup life under maximum power draw" },
      ],
      correctAnswer: "B",
      explanation: "Discrepancy monitoring detects contact bounce or welded mechanical contacts by ensuring both redundant channels open/close within milliseconds of each other. If one channel lags or fails to open, a safety fault is latched.",
    },
    {
      id: "q_mod_c_6",
      questionNumber: 6,
      totalInModule: 9,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "Why must a safety interlock system require a dedicated manual reset action rather than automatically restarting when a safety guard is re-closed?",
      options: [
        { key: "A", text: "To allow machinery to cool down after sudden shutdowns" },
        { key: "B", text: "To prevent unexpected machine restart while personnel might still be inside the hazard zone" },
        { key: "C", text: "To reset network IP packets dropped during the emergency event" },
        { key: "D", text: "To save electrical utility power during restart cycles" },
      ],
      correctAnswer: "B",
      explanation: "Under safety standards (e.g., ISO 13849 / IEC 62061), clearing an interlock trip must never immediately restart hazardous motion. A deliberate, supervised manual reset from outside the danger zone is mandatory.",
    },
    {
      id: "q_mod_c_7",
      questionNumber: 7,
      totalInModule: 9,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "What is the function of a 'watchdog timer' in an industrial safety microcontroller or PLC?",
      options: [
        { key: "A", text: "Logging shift timestamps for employee punch-card tracking" },
        { key: "B", text: "Automatically triggering a safe shutdown if the firmware hangs, loops infinitely, or crashes" },
        { key: "C", text: "Regulating the analog clock speed of fieldbus communication" },
        { key: "D", text: "Measuring cooling fan RPM and ambient room temperature" },
      ],
      correctAnswer: "B",
      explanation: "A watchdog timer expects periodic software keep-alive 'kicks'. If firmware hangs or encounters an unhandled fault, the watchdog timer expires and immediately forces all outputs to their de-energized safe state.",
    },
    {
      id: "q_mod_c_8",
      questionNumber: 8,
      totalInModule: 9,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "What does 'de-energize to trip' (positive safety principle) mean in critical safety instrumented systems?",
      options: [
        { key: "A", text: "Cutting AC mains voltage to the entire facility every evening" },
        { key: "B", text: "Requiring continuous electrical power to hold equipment in the run state, so that loss of power defaults to shutdown" },
        { key: "C", text: "Discharging all capacitors to ground before opening the electrical cabinet" },
        { key: "D", text: "Applying 24V DC to activate an emergency brake solenoid only during alarms" },
      ],
      correctAnswer: "B",
      explanation: "In de-energize-to-trip architecture, relays and coils are held energized during normal operation. A broken conductor, blown fuse, or blackout instantly drops the circuit, triggering a safe stop without needing active backup power.",
    },
    {
      id: "q_mod_c_9",
      questionNumber: 9,
      totalInModule: 9,
      module: "C",
      moduleTitle: "FAIL-SAFE PROTOCOL CHECK",
      prompt: "In functional safety (IEC 61508 / ISO 13849), what does the diagnostic coverage (DC) metric measure?",
      options: [
        { key: "A", text: "The geographic area covered by wireless security cameras" },
        { key: "B", text: "The percentage of dangerous failures that are automatically detected by internal diagnostics" },
        { key: "C", text: "The total number of hours a technician spends inspecting wiring annually" },
        { key: "D", text: "The physical thickness of the protective steel interlock enclosure" },
      ],
      correctAnswer: "B",
      explanation: "Diagnostic Coverage (DC) is the ratio of detected dangerous failure rate to total dangerous failure rate. Higher DC means the safety system detects and mitigates more hardware defects before they cause harm.",
    },
  ],
};
